# Generated by Django 4.2.7 on 2023-11-28 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plateforme', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Submission',
            new_name='Soumission',
        ),
        migrations.RenameModel(
            old_name='Visitor',
            new_name='Visiteur',
        ),
    ]
